### PR TITLE
Update contents.lr

### PR DESCRIPTION
**Pull request by francescomacri**
## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by francescomacri** [comment]
Watch out! Before merging, it is necessary to make sure that the correct page is replaced:  I was redirected to the original page in English, and accidentally suggested replacing the original (English) page, which of course I didn't intend to do. If you select a language, e. g. German, the menu does not display the command "Edit on GitHub". The only foreign languages pages that also display the "Edit on GitHub" command are Spanish and Portuguese - at least as far as I have seen.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
The translation looks good (from what I can tell); but as you've noticed, the edits are against the main content file, not creating a new translation. This is probably because there isn't an existing translation; the "edit on GitHub" link may only work if there is an existing document that can be edited.

**Comment by francescomacri** [comment]
Thank you very much for the hint, Russel. I would correct the problem as follows: I will create the missing file in my branch and test the changes with lektor in the virtual environment venv before submiddling. Afterwards I will close the commit #438. Does the suggested procedure make sense?

**Comment by freakboy3742** [comment]
The general process you've described makes sense; however, you don't need to create a new PR - if you push the update to the existing patch-5 branch, this PR will be updated.

**Comment by francescomacri** [comment]
I have updated the patch-5 branch: I have undone the change of the original text in English and added the contents+de.lr file for the German translation.

**Review by freakboy3742 — APPROVED** [review]
👍

**Pull request merged**
