### PR TITLE
Add mhsmith to team

### PR DESCRIPTION
**Pull request by mhsmith**
## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Welcome to the team!

**Comment by mhsmith** [comment]
Is there something else that needs to happen to move it to the live site?

**Comment by freakboy3742** [comment]
Hrm... it *should* have been auto deployed, and there wasn't an error running the action... so I'm not 100% sure what went wrong here. I'm guessing it's related to merging 2 PRs very close to one another.

I'm about to deploy the Q4 status update, so it should be cleaned up shortly.

**Comment by freakboy3742** [comment]
Well that didn't work... investigations continue.

**Comment by freakboy3742** [comment]
🤦 Naming error. `mhsmith.lr` -> `contents.lr`. Fix incoming.

**Pull request merged**
