### PR TITLE
Add simplified chinese to BeeWare.lektorproject

### PR DESCRIPTION
**Pull request by akaroka**
Update the existing "alternatives.zh" to be "alternatives.zh_TW" and  add  new entry "alternatives.zh_CN" for simplified chinese.

## PR Checklist:

- [ x ] All new features have been tested
- [ x ] All new features have been documented
- [ x ] I have read the **CONTRIBUTING.md** file
- [ x ] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
This looks good, and there's definitely a new entry in the pulldown menu that isn't colliding with zh_TW.

Submitting small, self contained PRs is really helpful - but in this case, the PR is a little bit *too* small :-) Could I ask you to merge those other two PRs (#462 and #463) into this one? That way, when I merge the initial "zh_CN" translation, there will be at least *some* content to verify that the translation is set up right (and isn't breaking "zh_TW").

**Comment by akaroka** [comment]
Done~ : D
More Mandarin translations will be updated in the future. 
Update one page or major section at a time.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks! 2 more things I've been able to pick up now that I can test the full site:

1. The menu is now showing 2 entries for 漢語 (because the zh_TW and zh_CN share a common alternative name "Chinese"). I'm not 100% certain how best to distinguish those two names - I know I've seen "Chinese (Traditional)" and "Chinese (Simplified)" on some lists, but I don't know if there's a better option (or how those options render as Hànzì)
 
2. The change of the alternative suffix has had the side effect of breaking all the existing `zh` translations. For example, there's a zh_TW translation of the homepage; but with this change, that content is longer visible. All the existing "+zh.lr" files will need to be renamed to "+zh_tw.lr" (I think... it might be "+zh_TW.lr" ... but you should be able to check that locally)

**Comment by akaroka** [comment]
In China, Traditional Chinese is used in Hong Kong(`zh_HK`), Macao(`zh_MO`) and Taiwan(`zh_TW`) while Simplified Chinese is mostly used in Mainland(`zh_CN`). Also Chinese is used in other country and area, for example, Singapore(`zh_SG`). However, it can be simply divided into Simplified Chinese(`zh_CHS`) and Traditional Chinese(`zh_CHT`). 
Of course, there is a little difference among different Chinese characters.

And I find a good explanation for the first problem.

https://github.com/getnikola/nikola/issues/1637#issue-62681560

> 
> Locale | Description
> -- | --
> zh-CN | Chinese (Simplified, PRC)
> zh-SG | Chinese (Simplified, Singapore)
> zh-TW | Chinese (Traditional, Taiwan)
> zh-HK | Chinese (Traditional, Hong Kong S.A.R.)
> zh-MO | Chinese (Traditional, Macao S.A.R.)
> 
> We see that zh-SG also uses Simplified Chinese, and all the rest use Traditional
> Chinese.
> It would be very easy to support all the Chinese locales by
> 
> 1. Adding support to a locale which uses Traditional Chinese, say `zh-TW`
> 2. The other Traditional Chinese locales (`zh-HK`, `zh-MO`) can then simply inherit
> `MESSAGES` from the `zh-TW` locale.
> 3. The same applies to `zh-SG`, which can just inherit from `zh-CN`.

For the second problem, I can help. 
The initial "zh_CN" translation can be merged later.

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
