### PR TITLE
[WIP] First time setup instructions for windows

### PR DESCRIPTION
**Pull request by bobm123**
This is a test PR to see the CI scripts run. It is currently missing some needed content and I will update shortly. Thanks - Bob M.

### CODE REVIEW

**Comment by goanpeca** [comment]
@bobm123 thanks for working on this. Adding the `[WIP]` prefix to the PR let us know that this is still a work in progress. You can give me a ping when done to go over this.

Cheers

**Comment by bobm123** [comment]
I need to fix my Python 2.7 install so I can run lektor locally. Please stand by...

**Comment by bobm123** [comment]
it seems both this branch and the main branch is failing several tests because of broken links. For example, https://2016.pyohio.org/schedule/ shows up on news\events\pyohio-2016

**Comment by goanpeca** [comment]
@bobm123 you are correct, let's try to fix 'em :-) now that they surfaced

- https://2016.pyohio.org/schedule/ -> https://www.pyohio.org/
- http://127.0.0.1:5000/news/buzz/2017-google-summer-of-code -> https://github.com/pybee/pybee.github.io/wiki
- https://www.youtube.com/watch?v=B3KBuQHHKx0 -> maybe https://www.youtube.com/watch?v=B3KBuQHHKx0 ? or look for a source on https://www.youtube.com/results?search_query=cheese+shop+monty+python

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue. 😄

**Pull request closed without merging**
