### PR TITLE
Add link to website PR target.

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Help new contributors find where they need to go. 

Signed-off-by: David Antonini <toonarmycaptain@hotmail.com>

### CODE REVIEW

**Comment by toonarmycaptain** [comment]
If that link is incorrect, or there is a preferred branch that can be used as default, let's change it.

**Comment by danyeaw** [comment]
@toonarmycaptain I think this link would have to be to the users Fork of beeware.github.io, and that would vary per user.

**Comment by toonarmycaptain** [comment]
Oh, you're right, sorry!
They'd have to click 'compare across forks' to be able to select their fork. I wonder if there's a way to specify that link dynamically if they're logged in...

**Comment by danyeaw** [comment]
@toonarmycaptain I am going to go ahead and close this. If there was a way to dynamically create a link - I'm not sure that it would be that helpful. I think users would fork, commit, push, and then create a PR. Linking to the end step doesn't add much.

**Comment by toonarmycaptain** [comment]
Agreed :)

**Pull request closed without merging**
