### PR TITLE
PR: Add Netlify build preview integration

### LINKED ISSUE #393: Add preview capability for PR changes
At present, if a user submits a PR, there's no way to validate that it renders correctly. 

We should add, as part of the PR test process, a rendering of the site that can be viewed and tested.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #393

image
image
image
Screen Shot 2020-07-06 at 20 56 40

### CODE REVIEW

**Comment by goanpeca** [comment]
Added netlify, it seems it is "tied" to my user and the team can only have 1 person. Let me know what email should I use to transfer it to.

Cheers! It was easy once I found what I needed, the dashboard is a mess... :-|

**Comment by freakboy3742** [comment]
That looks really good - thanks for digging into it (and it looks like the "details" of the netlify build check links to the sample site.

In terms of the limitations on Netlify - Who is the "user" in this sense that needs the email address? The person who submits the PR? Or the person who owns the account? i.e., would we need to have a user account for every contributor? That would seem to push us off the free tier pretty quickly...

**Comment by goanpeca** [comment]
>In terms of the limitations on Netlify - Who is the "user" in this sense that needs the email address? The person who submits the PR? Or the person who owns the account? i.e., would we need to have a user account for every contributor? That would seem to push us off the free tier pretty quickly...

For who owns the configuration of the service. I guess it should be you?

Currently this is what I see:
Screen Shot 2020-07-07 at 17 50 11

**Comment by freakboy3742** [comment]
Ok - I guess transferring to russell@keith-magee.com would make sense then.

**Comment by goanpeca** [comment]
>Ok - I guess transferring to russell@keith-magee.com would make sense then.

Ok it seems I cannot transfer it unless I create a new team and they charge me for that 🙄. It is probably better if I delete the site and you create the configuration? I left the screenshots on the top for it's precise reason.

Let me know so I can delete it?

**Comment by freakboy3742** [comment]
Ok - I've now set this up; I think you need to delete your version before I can claim the "beeware" name.

**Comment by goanpeca** [comment]
Deleted :-) 

Claim time!

**Comment by freakboy3742** [comment]
Claimed!

**Pull request merged**
