### PR TITLE
Fixed menu bug (#292)

### LINKED ISSUE #292: Bugs in the website menu
I noticed a couple of bugs on the website menu:

- The menu position is fixed, so it can't be scrolled (possibly hiding bottom items, specially in landscape mode)
- I can't change to another language due to the dropdown menu opening mostly out of the bottom of the screen

In the screenshot below (captured on Google Chrome, in "responsive" mode), you can see how the menu is visible in portrait mode and how the language selection menu is not accessible (at least on Google Chrome):

clipboard01

### PR DESCRIPTION
**Pull request by dhawal-kamdar**
Changed some CSS properties to fix the menu bug, so that the user can scroll down the menu and change to another language.

The menu position was fixed, so it can't be scrolled (hiding bottom items)
We can't change to another language due to the dropdown menu opening mostly out of the bottom of the screen.
But now it can be scrolled and we can access bottom items and also change to another language using the dropdown.

This PR Fixes #292 

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by phildini** [comment]
Hi! Any chance you could provide before / after screen shots?

**Comment by freakboy3742** [comment]
@phildini You should be able to verify this by checking current website behavior vs the netlify deploy preview (one of the pre-build checks)

**Comment by dhawal-kamdar** [comment]
Hello @phildini  Here is the link for the netlify deploy preview
https://deploy-preview-459--beeware.netlify.app/
You can directly check this.

**Review by phildini — APPROVED** [review]

**Comment by dhawal-kamdar** [comment]
@phildini Thank you for merging my code.

**Pull request merged**
